# Generated by Django 5.1.1 on 2024-10-06 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
